### ISSUE TITLE
[Bug]: Orama modal z-index issue

### ISSUE THREAD

**Issue by jer3m01** [solidjs/solid-docs-next#661]
### 📝 Issue Description

On mobile (haven't tested desktop) the `Core` tab and the `soon` label of the section selector at the top of the screen is displayed above the search modal. 
This also prevents from clicking on the `X` close button.
Screenshot below.

### 📋 On which page(s) it occurs

all pages

### 🤔 Expected Behavior

search modal should have top priority

### 👀 Current Behavior

![Screenshot_20240408_125235_Firefox](https://github.com/solidjs/solid-docs-next/assets/33844379/186fb6e8-1cf7-4cc1-a0ef-1e25f02cf56d)

### 🖥️ Browser

Firefox 124 (Android)

**Comment by SaraVieira** [comment]
Seems to also have been fixed by https://github.com/solidjs/solid-docs-next/pull/660

cc @danieljcafonso

**Comment by jer3m01** [comment]
I'm still getting it on https://deploy-preview-660--solid-docs.netlify.app/
